# Generated by Django 3.1.3 on 2021-09-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20210927_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
