# Generated by Django 3.1.3 on 2021-10-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_profile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
    ]
