# Generated by Django 3.1.3 on 2021-10-01 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_id', models.CharField(max_length=10)),
                ('bible', models.CharField(max_length=30, null=True)),
                ('chapter', models.IntegerField(null=True)),
                ('verse', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture', models.CharField(max_length=400)),
                ('bodytext', models.TextField()),
                ('real_date', models.CharField(max_length=10)),
                ('d_week', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyBible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('n_week', models.CharField(max_length=10)),
                ('week', models.CharField(max_length=100)),
                ('bible_range', models.CharField(max_length=100)),
                ('bible_link', models.URLField(blank=True, null=True, verbose_name='Site URL')),
                ('specific_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
        migrations.CreateModel(
            name='WBsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=10)),
                ('bible_summary', models.TextField()),
                ('specific_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('bible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bible')),
                ('weeklybible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_research', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(null=True, related_name='voter_research', to=settings.AUTH_USER_MODEL)),
                ('weeklybible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible')),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
        migrations.CreateModel(
            name='PubsIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=10)),
                ('index_verse', models.CharField(max_length=50)),
                ('pi_title', models.CharField(max_length=50)),
                ('pi_link', models.URLField(blank=True, null=True, verbose_name='Publications Index URL')),
                ('specific_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('bible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bible')),
                ('weeklybible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible')),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation', models.TextField()),
                ('real_date', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_meditation', to=settings.AUTH_USER_MODEL)),
                ('scripture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neworld.scripture')),
                ('voter', models.ManyToManyField(null=True, related_name='voter_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.meditation')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.question')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.research')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neworld.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
