# Generated by Django 3.1.3 on 2021-10-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bible',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='verse',
        ),
    ]
