# Generated by Django 3.1.3 on 2021-10-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubsIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=10)),
                ('index_verse', models.CharField(max_length=50)),
                ('pi_title', models.CharField(max_length=50)),
                ('pi_link', models.URLField(blank=True, null=True, verbose_name='Publications Index URL')),
                ('specific_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('bible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bible')),
                ('weeklybible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible')),
            ],
        ),
    ]
