# Generated by Django 3.1.3 on 2021-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible',
            name='chapter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bible',
            name='verse',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
