# Generated by Django 3.1.3 on 2021-08-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripture',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_scripture', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripture',
            name='voter',
            field=models.ManyToManyField(related_name='voter_scripture', to=settings.AUTH_USER_MODEL),
        ),
    ]
