# Generated by Django 3.1.3 on 2021-08-26 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0002_auto_20210821_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_scripture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scripture',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_scripture', to=settings.AUTH_USER_MODEL),
        ),
    ]
