# Generated by Django 3.1.3 on 2021-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0002_pubsindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='chapter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bible',
            name='verse',
            field=models.IntegerField(null=True),
        ),
    ]
