# Generated by Django 3.1.3 on 2021-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0003_auto_20211001_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='chapter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bible',
            name='verse',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
