# Generated by Django 3.1.3 on 2021-08-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0003_auto_20210826_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripture',
            name='d_week',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
