# Generated by Django 3.1.3 on 2021-10-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0003_auto_20211003_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bible',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='verse',
        ),
    ]
