# Generated by Django 3.1.3 on 2021-10-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0004_auto_20211001_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bible',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='verse',
        ),
    ]
