# Generated by Django 3.1.3 on 2021-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0004_scripture_d_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('n_week', models.DateTimeField(max_length=10)),
                ('week', models.DateTimeField(max_length=50)),
                ('bible_range', models.CharField(max_length=500)),
            ],
        ),
    ]
