# Generated by Django 3.1.3 on 2021-10-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0006_comment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='research',
            name='group',
        ),
        migrations.AddField(
            model_name='answer',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meditation',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_research', to=settings.AUTH_USER_MODEL),
        ),
    ]
