# Generated by Django 3.1.3 on 2021-08-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0007_auto_20210831_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleweek',
            name='bible_range',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleweek',
            name='week',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
