# Generated by Django 3.1.3 on 2021-10-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0008_auto_20211010_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='research',
            name='group',
        ),
    ]
