# Generated by Django 3.1.3 on 2021-09-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0008_auto_20210831_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripture',
            name='author',
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_research', to=settings.AUTH_USER_MODEL)),
                ('bible_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bibleweek')),
                ('voter', models.ManyToManyField(null=True, related_name='voter_research', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_research', to='neworld.bibleweek')),
            ],
        ),
    ]
