# Generated by Django 3.1.3 on 2021-09-01 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0009_auto_20210901_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleweek',
            name='voter',
            field=models.ManyToManyField(null=True, related_name='voter_bibleweek', to=settings.AUTH_USER_MODEL),
        ),
    ]
