# Generated by Django 3.1.3 on 2021-09-01 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0010_bibleweek_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('n_week', models.CharField(max_length=10)),
                ('week', models.TextField()),
                ('bible_range', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('voter', models.ManyToManyField(null=True, related_name='voter_weeklybible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='research',
            name='bible_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible'),
        ),
        migrations.AlterField(
            model_name='research',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_research', to='neworld.weeklybible'),
        ),
        migrations.DeleteModel(
            name='BibleWeek',
        ),
    ]
