# Generated by Django 3.1.3 on 2021-09-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0011_auto_20210901_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.research'),
        ),
    ]
