# Generated by Django 3.1.3 on 2021-09-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0012_comment_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='bible_link',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
        migrations.AddField(
            model_name='weeklybible',
            name='bible_summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklybible',
            name='bible_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklybible',
            name='week',
            field=models.CharField(max_length=100),
        ),
    ]
