# Generated by Django 3.1.3 on 2022-02-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0013_auto_20220202_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
