# Generated by Django 3.1.3 on 2021-09-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0013_auto_20210902_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybible',
            name='bible_link',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='research',
            name='bible_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl_research', to='neworld.weeklybible'),
        ),
        migrations.AlterField(
            model_name='research',
            name='bible_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_research', to='neworld.weeklybible'),
        ),
    ]
