# Generated by Django 3.1.3 on 2021-09-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0014_auto_20210902_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_id', models.CharField(max_length=10)),
                ('bible', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=50)),
                ('verse', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='research',
            name='bible_link',
        ),
        migrations.RemoveField(
            model_name='research',
            name='week',
        ),
        migrations.RemoveField(
            model_name='weeklybible',
            name='bible_summary',
        ),
        migrations.RemoveField(
            model_name='weeklybible',
            name='voter',
        ),
        migrations.AddField(
            model_name='weeklybible',
            name='specific_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WBsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_chapter', models.CharField(max_length=10)),
                ('bible_summary', models.TextField()),
                ('specific_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField()),
                ('bible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bible')),
            ],
        ),
        migrations.AddField(
            model_name='weeklybible',
            name='bible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.bible'),
        ),
    ]
