# Generated by Django 3.1.3 on 2022-02-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0015_auto_20220202_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
