# Generated by Django 3.1.3 on 2021-09-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0015_auto_20210907_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklybible',
            old_name='bible',
            new_name='bible_id',
        ),
    ]
