# Generated by Django 3.1.3 on 2021-09-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0016_auto_20210908_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbsummary',
            name='bible_chapter',
        ),
        migrations.AddField(
            model_name='wbsummary',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_wbsummary', to='neworld.bible'),
        ),
    ]
