# Generated by Django 3.1.3 on 2021-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0017_auto_20210908_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible',
            name='bible',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bible',
            name='chapter',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bible',
            name='verse',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wbsummary',
            name='bible',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbsummary',
            name='chapter',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
