# Generated by Django 3.1.3 on 2022-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0017_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
