# Generated by Django 3.1.3 on 2022-03-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0018_customer_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybible',
            name='n_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weeklybible',
            name='year',
            field=models.IntegerField(),
        ),
    ]
