# Generated by Django 3.1.3 on 2021-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0018_auto_20210908_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybible',
            name='bible_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
