# Generated by Django 3.1.3 on 2021-09-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0019_auto_20210908_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsummary',
            name='n_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible'),
        ),
    ]
