# Generated by Django 3.1.3 on 2023-01-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0020_gpt_gptanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='voter',
        ),
    ]
