# Generated by Django 3.1.3 on 2021-09-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0020_wbsummary_n_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='n_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n_week_research', to='neworld.weeklybible'),
        ),
    ]
