# Generated by Django 3.1.3 on 2021-09-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0022_auto_20210911_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklybible',
            name='bible_id',
        ),
    ]
