# Generated by Django 3.1.3 on 2023-01-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0022_auto_20230102_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='group',
        ),
    ]
