# Generated by Django 3.1.3 on 2023-01-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0023_auto_20230102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptanswer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_gptanswer', to=settings.AUTH_USER_MODEL),
        ),
    ]
