# Generated by Django 3.1.3 on 2021-09-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0023_remove_weeklybible_bible_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wbsummary',
            old_name='n_week',
            new_name='weeklybible',
        ),
        migrations.RemoveField(
            model_name='research',
            name='bible_range',
        ),
        migrations.RemoveField(
            model_name='research',
            name='n_week',
        ),
        migrations.AddField(
            model_name='research',
            name='weeklybible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible'),
        ),
    ]
