# Generated by Django 3.1.3 on 2023-01-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0024_gptanswer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptanswer',
            name='user_id',
        ),
    ]
