# Generated by Django 4.2.30 on 2026-08-24 08:09

from django.conf import settings
from django.db import migrations, models


def collapse_scripture_duplicates(apps, schema_editor):
    """Keep one complete Scripture per date before the unique constraint is added."""
    Scripture = apps.get_model("neworld", "Scripture")
    Meditation = apps.get_model("neworld", "Meditation")
    duplicate_dates = (
        Scripture.objects.values("real_date")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )
    for duplicate in duplicate_dates:
        rows = list(Scripture.objects.filter(real_date=duplicate["real_date"]).order_by("id"))
        keeper = max(
            rows,
            key=lambda row: (
                bool(row.scripture and row.scripture.strip()),
                bool(row.bodytext and row.bodytext.strip()),
                len(row.scripture or ""),
                len(row.bodytext or ""),
                -row.id,
            ),
        )
        duplicate_ids = [row.id for row in rows if row.id != keeper.id]
        Meditation.objects.filter(scripture_id__in=duplicate_ids).update(scripture_id=keeper.id)
        Scripture.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neworld', '0025_remove_gptanswer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='voter',
            field=models.ManyToManyField(related_name='voter_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='voter',
            field=models.ManyToManyField(related_name='voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='voter',
            field=models.ManyToManyField(related_name='voter_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='voter',
            field=models.ManyToManyField(related_name='voter_gpt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gptanswer',
            name='voter',
            field=models.ManyToManyField(related_name='voter_gptanswer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='voter',
            field=models.ManyToManyField(related_name='voter_meditation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='research',
            name='voter',
            field=models.ManyToManyField(related_name='voter_research', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(collapse_scripture_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bible',
            constraint=models.UniqueConstraint(fields=('bible_id',), name='bible_bible_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activity__isnull', True), ('answer__isnull', True), ('customer__isnull', True), ('meditation__isnull', True), ('question__isnull', False), ('research__isnull', True)), models.Q(('activity__isnull', True), ('answer__isnull', False), ('customer__isnull', True), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', True)), models.Q(('activity__isnull', True), ('answer__isnull', True), ('customer__isnull', True), ('meditation__isnull', False), ('question__isnull', True), ('research__isnull', True)), models.Q(('activity__isnull', True), ('answer__isnull', True), ('customer__isnull', True), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', False)), models.Q(('activity__isnull', True), ('answer__isnull', True), ('customer__isnull', False), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', True)), models.Q(('activity__isnull', False), ('answer__isnull', True), ('customer__isnull', True), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', True)), _connector='OR'), name='comment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='scripture',
            constraint=models.UniqueConstraint(fields=('real_date',), name='scripture_real_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='weeklybible',
            constraint=models.UniqueConstraint(fields=('year', 'n_week'), name='weeklybible_year_week_uniq'),
        ),
    ]
