# Generated by Django 3.1.3 on 2021-09-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0025_auto_20210916_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AlterModelOptions(
            name='meditation',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
        migrations.AlterModelOptions(
            name='weeklybible',
            options={'permissions': [('can_publish', 'Can Publish Posts'), ('can_change', 'Can Change Posts'), ('can_view', 'Can View Posts'), ('can_delete', 'Can Delete Posts')]},
        ),
    ]
