# Generated by Django 3.1.3 on 2021-09-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0026_auto_20210917_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripture',
            name='voter',
        ),
        migrations.AddField(
            model_name='scripture',
            name='weeklybible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neworld.weeklybible'),
        ),
    ]
