# Generated by Django 4.2.30 on 2026-08-28 13:26

from django.db import migrations, models


def delete_removed_feature_comments(apps, schema_editor):
    """Remove comments whose only target belongs to a removed feature."""
    Comment = apps.get_model('neworld', 'Comment')
    Comment.objects.filter(customer__isnull=False).delete()
    Comment.objects.filter(activity__isnull=False).delete()


def delete_removed_feature_metadata(apps, schema_editor):
    """Remove stale Django content types and their permissions for removed models."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='neworld',
        model__in=['activity', 'customer', 'gpt', 'gptanswer'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0026_alter_activity_voter_alter_answer_voter_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_removed_feature_comments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='activity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='group',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gpt',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='gpt',
        ),
        migrations.RemoveField(
            model_name='gptanswer',
            name='voter',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_exactly_one_target',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='customer',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('answer__isnull', True), ('meditation__isnull', True), ('question__isnull', False), ('research__isnull', True)), models.Q(('answer__isnull', False), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', True)), models.Q(('answer__isnull', True), ('meditation__isnull', False), ('question__isnull', True), ('research__isnull', True)), models.Q(('answer__isnull', True), ('meditation__isnull', True), ('question__isnull', True), ('research__isnull', False)), _connector='OR'), name='comment_exactly_one_target'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Gpt',
        ),
        migrations.DeleteModel(
            name='GptAnswer',
        ),
        migrations.RunPython(delete_removed_feature_metadata, migrations.RunPython.noop),
    ]
