# Generated by Django 3.1.3 on 2021-09-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0027_auto_20210920_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripture',
            name='weeklybible',
        ),
    ]
