# Generated by Django 3.1.3 on 2021-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0030_pubsindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsindex',
            name='chapter',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
