# Generated by Django 3.1.3 on 2021-09-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0031_auto_20210929_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubsindex',
            name='index_verse',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
