# Generated by Django 3.1.3 on 2021-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworld', '0032_pubsindex_index_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible',
            name='bible',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
